### ISSUE TITLE
Txt files cannot be opened with notepad

### ISSUE THREAD

**Issue by JiriVanek** [G-Node/WinGIN#150]
The windows notepad have issues with txt files in mounted repository (with dokan); the file could be opened with different editor (notepad++, wordpad) or through path without dokan mounting point...

**Comment by gwappa** [comment]
Hi, here the issue is a bit severer on my Windows 10 computer: 

- Even a text file (.txt, .md) cannot be opened through the Dokan mountpoint.
   - When I try to open by a double-click (or "Open" from the contextual menu)...
      - the cursor turns into a "busy cursor" for <1 sec
      - but it just does not open anything
      - without any error message.
   - When I select "Edit" from the contextual menu...
      - Notepad complains that "a system cannot find the content"
- When I tried opening a video file (.mp4) in VLC...
   - it says "VLC is unable to open the MRL".
- From the real repository (i.e. not through Dokan) it works fine, as it has been reported above.

Just in case it matters: I disable OneDrive when using WinGIN (because of a weird account problem).
I don't know whether or not I am using WinGIN in the 64-bit scheme.

[version info]

GIN command line client 1.9 Build 001415 (8725f3b9e37356add58aaccb75df77b699bda838)
  git: 2.18.0.windows.1
  git-annex: 7.20190627-g831e6746f

 WinGIN version 1.1.99.0 (with Dokan 1.1.0.2000)

**Comment by JiriVanek** [comment]
Hi, not sure about the video files issues, but the text files are fixed in new version of Dokan library.... I made new branch with new version of dokan (https://github.com/JiriVanek/WinGIN/tree/dokan_update) and so far it looks promising, but still a lot of testing before release
